### PR TITLE
#165369162 setup travis

### PR DESCRIPTION
**Pull request by engjames**
**What does this PR do?**
-add Travis file to the project
[Delivers #165369162]

**Description of Task to be completed?**
-update travis.py with the relevant requirements
Screenshot 2019-04-17 at 14 34 17

**What are the relevant pivotal tracker stories?**
#165369162

### CODE REVIEW

**Comment by mwinel** [comment]
Please ensure that you follow the git conventions when you are writing your commit messages and creating your PRs.

Here is a link for reference.
https://github.com/mirest/ah-haven-space-sprinters/wiki/Code-Conventions

**Comment by KabohaJeanMark** [comment]
Thanks for the work on travis.yml setup file. The file is okay. 
The reason the build is failing is because we are waiting for the merge of the PR with code on database setup to postgresql instead of sqlite. 
This will soon be resolved in @3Nakajugo's PR .

**Comment by KabohaJeanMark** [comment]
Great work on following the conventions on the branch naming and commit message.
You should improve the PR message by starting with the story id. 
A sample is below.
Screen Shot 2019-04-17 at 9 55 38 AM

**Comment by mwinel** [comment]
Please remember to begin with your story id when creating your PR title next time...

**Comment by 3Nakajugo** [comment]
travis build passes, Great Job!

**Pull request merged**
